name: Automate Dependency Updates

on:
  pull_request:
    paths:
      - package.json

jobs:
  checks:
    name: Check 4 Changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
      - run: npm ci
      - run: make
      - run: git diff --exit-code

  automerge:
    name: Auto Merge Pull Request
    runs-on: ubuntu-latest
    needs: checks
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.12.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: dependabot
          MERGE_METHOD: rebase
